// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcndcepbgqonylvdkkay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjbmRjZXBiZ3FvbnlsdmRra2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTczODYsImV4cCI6MjA2ODM5MzM4Nn0.Bw960rLw9p_zS4f0bGF96sxoLZA-jQJ387MFME6kD0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});